server {
    host: 127.0.0.1
    port: 8081
    server_name: localhost
    error_page_404: /errors/404.html
    error_page_400: /errors/400.html
    error_page_403: /errors/403.html
    error_page_405: /errors/405.html
    error_page_413: /errors/413.html
    error_page_500: /errors/500.html
    client_max_body_size: 1048576
    
    route / {
        methods: GET POST
        root: ./www
        index: index.html
        autoindex: on
    }
    
    route /upload {
        methods: POST
        root: /var/uploads
    }
    
    route /cgi-bin {
        methods: GET POST
        root: ./cgi-bin
        cgi_extension: .py python3
    }

    route /site {
        methods: GET
        root: ./www/site
        index: index.html
        autoindex: on
    }
}
