server {
    host: 127.0.0.1
    port: 8080
    server_name: localhost
    error_page_404: /errors/404.html
    client_max_body_size: 1048576
    
    route / {
        methods: GET POST
        root: ./www
        index: index.html
        autoindex: on
    }
    
    route /upload {
        methods: POST
        root: /var/uploads
    }
    
    route /cgi-bin {
        methods: GET POST
        root: ./cgi-bin
        cgi_extension: .py python3
    }
}
